### ISSUE TITLE
Investigate reader errors

### ISSUE THREAD

**Issue by ditac** [opendistro-for-elasticsearch/performance-analyzer-rca#43]
We see the following errors when processing events.

[ERROR][c.a.o.e.p.r.ReaderMetricsProcessor] READER PROCESSOR ERROR. NEEDS DEBUGGING Other ExceptionCode: org.jooq.exception.DataAccessException: SQL [select Direction, sum(Net_PacketRate6) sum_Net_PacketRate6, avg(Net_PacketRate6) avg_Net_PacketRate6, min(Net_PacketRate6) min_Net_PacketRate6, max(Net_PacketRate6) max_Net_PacketRate6 from IP_METRICS157
8517215000 where Net_PacketRate6 is not null group by Direction]; [SQLITE_ERROR] SQL error or missing database (no such table: IP_METRICS1578517215000).
org.jooq.exception.DataAccessException: SQL [select Direction, sum(Net_PacketRate6) sum_Net_PacketRate6, avg(Net_PacketRate6) avg_Net_PacketRate6, min(Net_PacketRate6) min_Net_PacketRate6, max(Net_PacketRate6) max_Net_PacketRate6 from IP_METRICS1578517215000 where Net_PacketRate6 is not null group by Direction]; [SQLITE_ERROR] SQL error or missing database (no such table: IP_
METRICS1578517215000)
        at org.jooq_3.10.1.SQLITE.debug(Unknown Source) ~[?:?]
        at org.jooq.impl.Tools.translate(Tools.java:2199) ~[jooq-3.10.1.jar:?]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:701) ~[jooq-3.10.1.jar:?]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:358) ~[jooq-3.10.1.jar:?]
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:314) ~[jooq-3.10.1.jar:?]
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2594) ~[jooq-3.10.1.jar:?]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.MetricsEmitter.emitNodeMetrics(MetricsEmitter.java:570) ~[OpenDistroPerformanceAnalyzerEngine.jar:?]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor.emitNodeMetrics(ReaderMetricsProcessor.java:908) ~[OpenDistroPerformanceAnalyzerEngine.jar:?]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor.emitMetrics(ReaderMetricsProcessor.java:442) ~[OpenDistroPerformanceAnalyzerEngine.jar:?]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor.processMetrics(ReaderMetricsProcessor.java:623) ~[OpenDistroPerformanceAnalyzerEngine.jar:?]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.reader.ReaderMetricsProcessor.run(ReaderMetricsProcessor.java:138) [OpenDistroPerformanceAnalyzerEngine.jar:?]
        at com.amazon.opendistro.elasticsearch.performanceanalyzer.PerformanceAnalyzerApp$1.run(PerformanceAnalyzerApp.java:85) [OpenDistroPerformanceAnalyzerEngine.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: IP_METRICS1578517215000)
        at org.sqlite.core.DB.newSQLException(DB.java:918) ~[sqlite-jdbc-3.13.0-SNAPSHOT.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:930) ~[sqlite-jdbc-3.13.0-SNAPSHOT.jar:?]
        at org.sqlite.core.DB.throwex(DB.java:895) ~[sqlite-jdbc-3.13.0-SNAPSHOT.jar:?]
        at org.sqlite.core.NativeDB.prepare(Native Method) ~[sqlite-jdbc-3.13.0-SNAPSHOT.jar:?]
        at org.sqlite.core.DB.prepare(DB.java:227) ~[sqlite-jdbc-3.13.0-SNAPSHOT.jar:?]
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41) ~[sqlite-jdbc-3.13.0-SNAPSHOT.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[sqlite-jdbc-3.13.0-SNAPSHOT.jar:?]
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[sqlite-jdbc-3.13.0-SNAPSHOT.jar:?]
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48) ~[sqlite-jdbc-3.13.0-SNAPSHOT.jar:?]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254) ~[sqlite-jdbc-3.13.0-SNAPSHOT.jar:?]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226) ~[sqlite-jdbc-3.13.0-SNAPSHOT.jar:?]
        at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:106) ~[jooq-3.10.1.jar:?]
        at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:70) ~[jooq-3.10.1.jar:?]
        at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:230) ~[jooq-3.10.1.jar:?]
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:316) ~[jooq-3.10.1.jar:?]
        ... 9 more

**Comment by ktkrg** [comment]
Closing as not reproducible.
